"""
arc.stubs
-----------------
`arc stubs` — regenerates arc/__init__.pyi so `arc.<capability>` gets real
IDE/type-checker visibility (autocomplete, parameter hints, "go to
definition") even though it's resolved dynamically at runtime via
arc/__init__.py's own __getattr__ (PEP 562) — which no static analyzer
can see through on its own.

Single source of truth, deliberately: nothing here is a second
declaration of a plugin's API. Every capability's real, already-typed
provider class — the exact object `kernel.export(name, instance, ...)`
was given, which every plugin's register() already calls — is
introspected directly. A plugin author writes nothing extra to get this;
there is no parallel manifest to keep in sync, on purpose (the same
"declare it once, by the owning code" posture as everywhere else in this
project — a duplicate declaration is a bug waiting to drift, not a
feature).

Scoped to THIS project's plugins.lock, not a hypothetical union of every
plugin that has ever existed — a project that never installed `mail`
correctly gets no `arc.mail` suggested by autocomplete at all, the same
as at runtime.

Needs a real arc.boot() (imports every enabled plugin for real, to get
real classes) but never open()s a single capability — no DB/Redis
connection is touched, unlike `arc doctor --deep`, which briefly opens
everything to report live health.

Wired to auto-regenerate from several call sites (arc/cli.py) so it can't
silently go stale: `arc build`, `arc install`, `arc new-plugin`, `arc
plugin enable`/`disable`, `arc restart`. Each of those treats a stub
-generation failure as a non-fatal warning — a broken plugin mid-edit
failing to import must not also fail the command that triggered this,
which almost always has a more important job. Also runnable directly,
where a failure IS fatal (you asked for exactly this, nothing else ran).
"""

from __future__ import annotations

import warnings
from pathlib import Path

import typer
from rich.console import Console

from .kernel import ArcAdvisory, Kernel
from .runtime import BootError, find_project_root

console = Console()
err_console = Console(stderr=True, style="bold red")

_GENERATED_HEADER = '''"""
GENERATED FILE — DO NOT EDIT BY HAND.

Regenerated by `arc stubs` — also run automatically by `arc build`, `arc
install`, `arc new-plugin`, `arc plugin enable`/`disable`, and `arc
restart`, so it should never go stale. If it looks wrong or out of date,
run `arc stubs` again rather than hand-editing this file: any manual
change here is silently overwritten the next time something regenerates
it, and this file is gitignored (it's specific to THIS project's
currently enabled plugins, not something to commit or merge).

Exists purely to give `arc.<capability>` (resolved dynamically at runtime
via arc/__init__.py's own __getattr__, PEP 562) real IDE/type-checker
visibility for exactly the plugins this project currently has enabled
(.arc/plugins.lock). Every name below maps straight to the real,
already-typed provider class each plugin's own register() exports —
nothing here is a second declaration of any plugin's API surface.
"""

'''

_STATIC_REEXPORTS = '''from typing import Any

from . import codec as codec
from . import events as events
from . import health as health
from . import log as log
from .kernel import ArcAdvisory as ArcAdvisory
from .kernel import Capability as Capability
from .kernel import ExportError as ExportError
from .kernel import Kernel as Kernel
from .kernel import KernelError as KernelError
from .resolver import BootPlan as BootPlan
from .resolver import PluginSpec as PluginSpec
from .resolver import ResolutionError as ResolutionError
from .runtime import BootError as BootError
from .runtime import boot as boot
from .runtime import find_project_root as find_project_root
from .runtime import shutdown as shutdown

__version__: str

def __getattr__(name: str) -> Any: ...
'''


def _capability_stub_lines(kernel: Kernel) -> tuple[list[str], list[str]]:
    """(import lines, attribute declaration lines) for every currently
    resolved capability, keyed off the REAL class kernel.export() was
    given. Each import is aliased by capability name (`_cap_<name>`) so
    two plugins whose provider classes happen to share a bare class name
    can never collide in the generated file. A capability exported as a
    plain `object()` (seen in this project's own test fixtures) or a
    class that isn't reachable by its own qualname (e.g. defined inside a
    function) falls back to `Any` — honest about what's actually known,
    not a guess."""
    imports: list[str] = []
    attrs: list[str] = []
    for name, cap in sorted(kernel.capabilities().items()):
        cls = type(cap.instance)
        module = cls.__module__
        qualname = cls.__qualname__
        if module == "builtins" or "." in qualname or "<locals>" in qualname:
            attrs.append(f"{name}: Any")
            continue
        alias = f"_cap_{name}"
        imports.append(f"from {module} import {qualname} as {alias}")
        attrs.append(f"{name}: {alias}")
    return imports, attrs


def generate(root: Path) -> Path:
    """Boots for real (imports every enabled plugin, never opens a single
    connection) and writes arc/__init__.pyi next to arc/__init__.py.
    Returns the path written. Raises BootError if boot itself would fail
    — the same failure this project already surfaces everywhere else
    that boots; nothing new to handle here."""
    import arc

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", ArcAdvisory)
        kernel = arc.boot(project_root=root, force=True)
    try:
        imports, attrs = _capability_stub_lines(kernel)
    finally:
        arc.shutdown()

    body = _GENERATED_HEADER + _STATIC_REEXPORTS
    if imports:
        body += "\n# --- capabilities resolved from this project's plugins.lock ---\n"
        body += "\n".join(imports) + "\n\n"
        body += "\n".join(attrs) + "\n"

    stub_path = Path(arc.__file__).parent / "__init__.pyi"
    stub_path.write_text(body)
    return stub_path


def stubs() -> None:
    """Regenerate arc/__init__.pyi from this project's currently enabled
    plugins.lock — see this module's own docstring for the full picture."""
    root = find_project_root()
    if root is None:
        err_console.print(
            "Not inside an ARC project — no .arc/arc.toml found in the current "
            "directory or any parent."
        )
        raise typer.Exit(code=1)
    try:
        path = generate(root)
    except BootError as exc:
        err_console.print(f"Could not generate stubs — boot itself would fail: {exc}")
        raise typer.Exit(code=1) from exc
    console.print(f"[bold green]Wrote {path}[/bold green]")
