"""
arc.uuid7
-----------------
Time-ordered UUIDs (RFC 9562 UUIDv7) — the same scheme pgdb's own
arc_uuid_generate_v7() (plugins/pgdb/pgdb/ddl.py) already stamps onto
every table's `id` column server-side by default, reproduced here
bit-for-bit: bytes 0-5 are a 48-bit big-endian milliseconds-since-Unix-
epoch timestamp, byte 6's high nibble is the version (0111), byte 8's top
two bits are the RFC 4122 variant (10), every remaining bit is
cryptographically random. A value generated by either side decodes
identically on the other.

Why this exists client-side at all, given Postgres already generates
these by default: a caller that needs a real id BEFORE the INSERT happens
(building a batch of related rows in memory, correlating a client-
generated id across two systems before either is written) has to mint one
itself rather than round-trip to the database purely to get an id.

Stateless: no project binding needed, works even before arc.boot() —
same posture as arc.codec.
"""

from __future__ import annotations

import os
import time
from datetime import datetime, timezone
from uuid import UUID


def generate() -> UUID:
    """A new, real UUIDv7 — sortable by creation time (millisecond
    resolution), indistinguishable from one pgdb/Postgres would have
    generated for the same row at the same instant."""
    ms = int(time.time() * 1000)
    b = bytearray(16)
    b[0:6] = ms.to_bytes(6, "big")
    b[6:16] = os.urandom(10)
    b[6] = (b[6] & 0x0F) | 0x70  # version nibble -> 7
    b[8] = (b[8] & 0x3F) | 0x80  # RFC 4122 variant bits
    return UUID(bytes=bytes(b))


def extract_timestamp(value: UUID | str) -> datetime:
    """The real creation instant embedded in a UUIDv7 — a timezone-aware
    UTC datetime, millisecond precision (the format's own resolution).
    Works identically on a value this module generated or one Postgres
    did (same layout either way).

    Raises ValueError if `value` isn't actually a version-7 UUID — a v4
    id has no embedded timestamp; returning a nonsense "timestamp" for
    one would be worse than refusing outright."""
    u = value if isinstance(value, UUID) else UUID(str(value))
    if u.version != 7:
        raise ValueError(f"{u} is a UUID version {u.version}, not version 7 — no timestamp to extract.")
    ms = int.from_bytes(u.bytes[:6], "big")
    return datetime.fromtimestamp(ms / 1000, tz=timezone.utc)
