"""
arc.plugins.psqldb.base
==================
The single SQLAlchemy ``DeclarativeBase`` shared by every Arc-managed table.
Tables are generated by the schema compiler from JSON — there are no
hand-written model files.
"""

from __future__ import annotations

from sqlalchemy.orm import DeclarativeBase


class ArcBase(DeclarativeBase):
    """Shared declarative base for all Arc tables."""

    pass
